-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 14:58:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `or_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `or_projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `organization_id` INT NOT NULL,
  `name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `team_id` INT NOT NULL,
  `attributes` JSON NULL,
  `archived` TINYINT(1) NULL,
  `archived_at` DATETIME NULL,
  `archived_by_user_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `owner_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_team_id_idx` (`team_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_archived_by_user_id_idx` (`archived_by_user_id` ASC),
  INDEX `fk_owner_id_idx` (`owner_id` ASC),
  CONSTRAINT `fk_team_id_or_projects`
    FOREIGN KEY (`team_id`)
    REFERENCES `teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_projects`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archived_by_user_id_or_projects`
    FOREIGN KEY (`archived_by_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_id_or_projects`
    FOREIGN KEY (`owner_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `or_folders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `or_folders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `project_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `attributes` JSON NULL,
  `archived` TINYINT(1) NULL,
  `archived_at` DATETIME NULL,
  `archived_by_user_id` INT NULL,
  `organization_id` INT NOT NULL,
  `owner_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_id_idx` (`project_id` ASC),
  INDEX `fk_archived_by_user_id_idx` (`archived_by_user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_owner_id_idx` (`owner_id` ASC),
  CONSTRAINT `fk_organization_id_or_folders`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_id_or_folders`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archived_by_user_id_or_folders`
    FOREIGN KEY (`archived_by_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_owner_id_or_folders`
    FOREIGN KEY (`owner_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`or_revisions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `or_revisions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `file_id` INT NOT NULL,
  `resource_id` INT NULL,
  `name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` VARCHAR(50) NULL,
  `content_type` VARCHAR(200) NOT NULL,
  `content_length` INT NULL,
  `upload_status` VARCHAR(50) NULL,
  `organization_id` INT NOT NULL,
  `url` VARCHAR(400) NULL,
  `attributes` JSON NULL,
  `archived` TINYINT(1) NULL,
  `archived_at` DATETIME NULL,
  `archived_by_user_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `owner_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_id_idx` (`file_id` ASC),
  INDEX `fk_resource_id_idx` (`file_id` ASC),
  INDEX `fk_archived_by_user_id_idx` (`archived_by_user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_owner_id_idx` (`owner_id` ASC),
  CONSTRAINT `fk_resource_id_or_revisions`
    FOREIGN KEY (`resource_id`)
    REFERENCES `resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_revisions`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_id_or_revisions`
    FOREIGN KEY (`file_id`)
    REFERENCES `or_files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archived_by_user_id_or_revisions`
    FOREIGN KEY (`archived_by_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_id_or_revisions`
    FOREIGN KEY (`owner_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`or_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `or_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `project_id` INT NOT NULL,
  `head_revision_id` INT NULL,
  `attributes` JSON NULL,
  `archived` TINYINT(1) NULL,
  `archived_at` DATETIME NULL,
  `archived_by_user_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `organization_id` INT NOT NULL,
  `owner_id` INT NULL,
  PRIMARY KEY (`id`, `created_at`, `updated_at`),
  INDEX `fk_project_id_idx` (`project_id` ASC),
  INDEX `fk_head_revision_id_idx` (`head_revision_id` ASC),
  INDEX `fk_archived_by_user_id_idx` (`archived_by_user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_owner_id_idx` (`owner_id` ASC),
  CONSTRAINT `fk_project_id_or_files`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_head_revision_id_or_files`
    FOREIGN KEY (`head_revision_id`)
    REFERENCES `or_revisions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archived_by_user_id_or_files`
    FOREIGN KEY (`archived_by_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_files`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_id_or_files`
    FOREIGN KEY (`owner_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`or_parent_folders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `or_parent_folders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(100) NOT NULL,
  `parent_folder_id` INT NOT NULL,
  `child_entity_id` INT NOT NULL,
  `child_entity_type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parent_folder_id_idx` (`parent_folder_id` ASC),
  CONSTRAINT `fk_parent_folder_id_or_parent_folders`
    FOREIGN KEY (`parent_folder_id`)
    REFERENCES `or_folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `or_relations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(100) NOT NULL,
  `rel` VARCHAR(30) NOT NULL,
  `inverse_rel` VARCHAR(30) NULL,
  `source_id` INT NOT NULL,
  `source_type` VARCHAR(20) NOT NULL,
  `target_id` INT NOT NULL,
  `target_type` VARCHAR(20) NOT NULL,
  `user_id` INT NOT NULL,
  `organization_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  CONSTRAINT `fk_user_id_or_relations`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_relations`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_id_or_relations`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `or_tags` (
 `id` INT NOT NULL AUTO_INCREMENT,
 `uuid` VARCHAR(36) NOT NULL,
 `user_id` INT NOT NULL,
 `organization_id` INT NOT NULL,
 `project_id` INT NOT NULL,
 `entity_id` INT NOT NULL,
 `entity_type` VARCHAR(20) NOT NULL,
 `tag` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `created_at` DATETIME NOT NULL,
 `updated_at` DATETIME NOT NULL,
 PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_project_id_idx` (`project_id` ASC),
  CONSTRAINT `fk_user_id_or_tags`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_tags`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_id_or_tags`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `or_timeline_events` (
 `id` INT NOT NULL AUTO_INCREMENT,
 `uuid` VARCHAR(36) NOT NULL,
 `user_id` INT NOT NULL,
 `organization_id` INT NOT NULL,
 `project_id` INT NOT NULL,
 `entity_id` INT NOT NULL,
 `entity_type` VARCHAR(20) NOT NULL,
 `name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `notes` VARCHAR(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `start` DATETIME NOT NULL,
 `end` DATETIME NULL,
 `created_at` DATETIME NOT NULL,
 `updated_at` DATETIME NOT NULL,
 PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_project_id_idx` (`project_id` ASC),
  CONSTRAINT `fk_user_id_or_timeline_events`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_timeline_events`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_id_or_timeline_events`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `or_notes` (
 `id` INT NOT NULL AUTO_INCREMENT,
 `uuid` VARCHAR(36) NOT NULL,
 `user_id` INT NOT NULL,
 `organization_id` INT NOT NULL,
 `project_id` INT NOT NULL,
 `entity_id` INT NOT NULL,
 `entity_type` VARCHAR(20) NOT NULL,
 `text` VARCHAR(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `timestamp` DATETIME NOT NULL,
 `created_at` DATETIME NOT NULL,
 `updated_at` DATETIME NOT NULL,
 PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_project_id_idx` (`organization_id` ASC),
  CONSTRAINT `fk_user_id_or_notes`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_notes`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_id_or_notes`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `or_properties` (
 `id` INT NOT NULL AUTO_INCREMENT,
 `uuid` VARCHAR(36) NOT NULL,
 `user_id` INT NOT NULL,
 `organization_id` INT NOT NULL,
 `project_id` INT NOT NULL,
 `entity_id` INT NOT NULL,
 `entity_type` VARCHAR(20) NOT NULL,
 `property_key` VARCHAR(1000) NOT NULL,
 `property_value` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
 `created_at` DATETIME NOT NULL,
 `updated_at` DATETIME NOT NULL,
 PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  CONSTRAINT `fk_user_id_or_properties`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_properties`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_id_or_properties`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `or_sources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(100) NOT NULL,
  `name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `attributes` JSON NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `archived` TINYINT(1) NULL,
  `archived_at` DATETIME NULL,
  `archived_by_user_id` INT NULL,
  `owner_id` INT NULL,
  `organization_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_archived_by_user_id_idx` (`archived_by_user_id` ASC),
  INDEX `fk_owner_id_idx` (`owner_id` ASC),
  CONSTRAINT `fk_organization_id_or_sources`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archived_by_user_id_or_sources`
    FOREIGN KEY (`archived_by_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_id_or_sources`
    FOREIGN KEY (`owner_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `or_source_projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_id_idx` (`project_id` ASC),
  INDEX `fk_source_id_idx` (`source_id` ASC),
  CONSTRAINT `fk_project_id_or_source_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_source_id_or_source_projects`
    FOREIGN KEY (`source_id`)
    REFERENCES `or_sources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `or_activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `project_id` INT NULL,
  `attributes` JSON NULL,
  `archived` TINYINT(1) NULL,
  `archived_at` DATETIME NULL,
  `archived_by_user_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `organization_id` INT NOT NULL,
  `owner_id` INT NULL,
  PRIMARY KEY (`id`, `created_at`, `updated_at`),
  INDEX `fk_project_id_idx` (`project_id` ASC),
  INDEX `fk_archived_by_user_id_idx` (`archived_by_user_id` ASC),
  INDEX `fk_organization_id_idx` (`organization_id` ASC),
  INDEX `fk_owner_id_idx` (`owner_id` ASC),
  CONSTRAINT `fk_project_id_or_activities`
    FOREIGN KEY (`project_id`)
    REFERENCES `or_projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archived_by_user_id_or_activities`
    FOREIGN KEY (`archived_by_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_id_or_activities`
    FOREIGN KEY (`organization_id`)
    REFERENCES `organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_id_or_activities`
    FOREIGN KEY (`owner_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
