version: '2'

services:
  web:
    build:
      image: web
      dockerfile: Dockerfile
    links:
      - db
    encrypted_env_file: dev.env.encrypted

  db:
    image: mysql

#  pubsub:
#    image: niallmccullagh/docker-google-cloud-emulators:latest
#    ports:
#      - "8538:8538"
#    command: /bin/bash -c "gcloud config set project emulator && gcloud beta emulators pubsub start --data-dir /mnt/data/pubsub --host-port 0.0.0.0:8538"

  gcr_dockercfg:
    image: codeship/gcr-dockercfg-generator
    add_docker: true
    encrypted_env_file: google-credentials.encrypted

  gke-deploy:
    build:
      image: deploy
      dockerfile: gke-deploy-Dockerfile
    encrypted_env_file: google-credentials.encrypted
    add_docker: true
    volumes:
      - ./deploy:/deploy
