version: '2'

services:
  web:
    build:
      image: web
      dockerfile: Dockerfile
    depends_on:
      - db
    encrypted_env_file: dev.env.encrypted

  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="1"
      - MYSQL_USER=webapi
      - MYSQL_PASSWORD=webapipass
      - MYSQL_DATABASE=ovation_development
    ports:
      - "3306:3306"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  gcr-dockercfg:
    image: codeship/gcr-dockercfg-generator
    add_docker: true
    encrypted_env_file: google-credentials.encrypted

  gke-deploy:
    build:
      image: deploy
      dockerfile: Dockerfile.deploy
    encrypted_env_file: google-credentials.encrypted
    add_docker: true
    volumes:
      - ./deploy:/deploy
