FROM codeship/google-cloud-deployment
MAINTAINER support@ovation.io

RUN curl -O https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
RUN mkdir -p $HOME/go
ENV GOPATH=$HOME/go
ENV PATH=$PATH:$HOME/go/bin

RUN go get -u go.mozilla.org/sops/cmd/sops
