FROM codeship/google-cloud-deployment
MAINTAINER support@ovation.io

RUN apt-get update -y

RUN apt-get install -y git

RUN apt-get install -y wget

RUN wget https://go.mozilla.org/sops/dist/sops_2.0.9_amd64.deb
RUN dpkg -i ./sops_2.0.9_amd64.deb
