apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        env: {{ .Release.Namespace }}
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: {{ .Release.Name }}-service-key-secret
        - name: env-secrets
          secret:
            secretName: {{ .Release.Name }}-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["lein", "run"]
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            httpGet:
              path: /healthz
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: env-secrets
              mountPath: /var/secrets/env
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: ELASTICSEARCH_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: JWT_SECRET
            - name: MYSQL_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_DATABASE_NAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_PORT
            - name: MYSQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_SERVER
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: MYSQL_USERNAME
            - name: RAYGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: RAYGUN_API_KEY
            - name: DB_UPDATES_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DB_UPDATES_TOPIC
            - name: GOOGLE_CLOUD_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: GOOGLE_CLOUD_PROJECT_ID
            - name: OVATION_IO_HOST_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: OVATION_IO_HOST_URI
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
