apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  CLOUDANT_PASSWORD: {{ .Values.secret.CLOUDANT_PASSWORD  | b64enc | quote }}
  CLOUDANT_USERNAME: {{ .Values.secret.CLOUDANT_USERNAME  | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET  | b64enc | quote }}
  RAYGUN_API_KEY: {{ .Values.secret.RAYGUN_API_KEY  | b64enc | quote }}
  ELASTICSEARCH_URL: {{ .Values.secret.ELASTICSEARCH_URL }}

